// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../render/thread.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `drop`, `next`, `drop`
// These types are ignored because they are not used by any `pub` functions: `MicrophoneStream`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MicrophoneRender>>
@sealed
class MicrophoneRender extends RustOpaque {
  // Not to be used by end users
  MicrophoneRender.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MicrophoneRender.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MicrophoneRender,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MicrophoneRender,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_MicrophoneRenderPtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MicrophoneRender> newInstance(
          {required BigInt numberOfChannels,
          required double sampleRate,
          required SenderAudioBuffer sender}) =>
      RustLib.instance.api.webAudioApiIoMicrophoneMicrophoneRenderNew(
          numberOfChannels: numberOfChannels,
          sampleRate: sampleRate,
          sender: sender);

  Future<void> render({required S data}) => RustLib.instance.api
      .webAudioApiIoMicrophoneMicrophoneRenderRender(that: this, data: data);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < AudioBuffer >>>
@sealed
class SenderAudioBuffer extends RustOpaque {
  // Not to be used by end users
  SenderAudioBuffer.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SenderAudioBuffer.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SenderAudioBuffer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SenderAudioBuffer,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_SenderAudioBufferPtr,
  );
}
