// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../buffer.dart';
import '../param.dart';
import 'analyser.dart';
import 'audio_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_computed_freq`, `calculate_coefs`, `clone`, `fmt`, `default`, `fmt`, `clone`, `eq`, `assert_receiver_is_total_eq`, `default`, `from`, `clone`, `fmt`, `default`, `fmt`, `registration`, `channel_config`, `number_of_inputs`, `number_of_outputs`, `process`, `onmessage`
// These types are ignored because they are not used by any `pub` functions: `BiquadFilterRenderer`, `Coefficients`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BiquadFilterNode>>
@sealed
class BiquadFilterNode extends RustOpaque {
  // Not to be used by end users
  BiquadFilterNode.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BiquadFilterNode.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BiquadFilterNode,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BiquadFilterNode,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_BiquadFilterNodePtr,
  );

  /// Returns the detune audio parameter
  Future<AudioParam> detune() =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeDetune(
        that: this,
      );

  /// Returns the frequency audio parameter
  Future<AudioParam> frequency() =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeFrequency(
        that: this,
      );

  /// Returns the gain audio parameter
  Future<AudioParam> gain() =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeGain(
        that: this,
      );

  /// Returns the frequency response for the specified frequencies
  ///
  /// # Arguments
  ///
  /// * `frequency_hz` - frequencies for which frequency response of the filter should be calculated
  /// * `mag_response` - magnitude of the frequency response of the filter
  /// * `phase_response` - phase of the frequency response of the filter
  ///
  /// # Panics
  ///
  /// This function will panic if arguments' lengths don't match
  ///
  Future<void> getFrequencyResponse(
          {required F32 frequencyHz,
          required F32 magResponse,
          required F32 phaseResponse}) =>
      RustLib.instance.api
          .webAudioApiNodeBiquadFilterBiquadFilterNodeGetFrequencyResponse(
              that: this,
              frequencyHz: frequencyHz,
              magResponse: magResponse,
              phaseResponse: phaseResponse);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// returns a `BiquadFilterNode` instance
  ///
  /// # Arguments
  ///
  /// * `context` - audio context in which the audio node will live.
  /// * `options` - biquad filter options
  static Future<BiquadFilterNode> newInstance(
          {required C context, required BiquadFilterOptions options}) =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeNew(
          context: context, options: options);

  /// Returns the Q audio parameter
  Future<AudioParam> q() =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeQ(
        that: this,
      );

  /// biquad filter type setter
  ///
  /// # Arguments
  ///
  /// * `type_` - the biquad filter type (lowpass, highpass,...)
  Future<void> setType({required BiquadFilterType type}) =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeSetType(
          that: this, type: type);

  /// Returns the biquad filter type
  Future<BiquadFilterType> type() =>
      RustLib.instance.api.webAudioApiNodeBiquadFilterBiquadFilterNodeType(
        that: this,
      );
}

/// Options for constructing a [`BiquadFilterNode`]
class BiquadFilterOptions {
  final double q;
  final double detune;
  final double frequency;
  final double gain;
  final BiquadFilterType type;
  final AudioNodeOptions audioNodeOptions;

  const BiquadFilterOptions({
    required this.q,
    required this.detune,
    required this.frequency,
    required this.gain,
    required this.type,
    required this.audioNodeOptions,
  });

  @override
  int get hashCode =>
      q.hashCode ^
      detune.hashCode ^
      frequency.hashCode ^
      gain.hashCode ^
      type.hashCode ^
      audioNodeOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiquadFilterOptions &&
          runtimeType == other.runtimeType &&
          q == other.q &&
          detune == other.detune &&
          frequency == other.frequency &&
          gain == other.gain &&
          type == other.type &&
          audioNodeOptions == other.audioNodeOptions;
}

/// Biquad filter types
enum BiquadFilterType {
  /// Allows frequencies below the cutoff frequency to pass through and
  /// attenuates frequencies above the cutoff. (12dB/oct rolloff)
  lowpass,

  /// Frequencies above the cutoff frequency are passed through, but
  /// frequencies below the cutoff are attenuated. (12dB/oct rolloff)
  highpass,

  /// Allows a range of frequencies to pass through and attenuates the
  /// frequencies below and above this frequency range.
  bandpass,

  /// Allows all frequencies through, except for a set of frequencies.
  notch,

  /// Allows all frequencies through, but changes the phase relationship
  /// between the various frequencies.
  allpass,

  /// Allows all frequencies through, but adds a boost (or attenuation) to
  /// a range of frequencies.
  peaking,

  /// Allows all frequencies through, but adds a boost (or attenuation) to
  /// the lower frequencies.
  lowshelf,

  /// Allows all frequencies through, but adds a boost (or attenuation) to
  /// the higher frequencies.
  highshelf,
  ;
}
