// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../periodic_wave.dart';
import 'audio_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assert_valid_channel_count_mode`, `assert_valid_channel_count`, `assert_valid_channel_interpretation`, `assert_valid_number_of_channels`, `channel_config`, `clone`, `default`, `fmt`, `fmt`, `fmt`, `number_of_inputs`, `number_of_outputs`, `process`, `registration`, `set_channel_count_mode`, `set_channel_count`, `set_channel_interpretation`
// These types are ignored because they are not used by any `pub` functions: `ChannelSplitterRenderer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChannelSplitterNode>>
@sealed
class ChannelSplitterNode extends RustOpaque {
  // Not to be used by end users
  ChannelSplitterNode.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ChannelSplitterNode.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_ChannelSplitterNode,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_ChannelSplitterNode,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_ChannelSplitterNodePtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ChannelSplitterNode> newInstance(
          {required C context, required ChannelSplitterOptions options}) =>
      RustLib.instance.api.webAudioApiNodeChannelSplitterChannelSplitterNodeNew(
          context: context, options: options);
}

/// Options for constructing a [`ChannelSplitterNode`]
class ChannelSplitterOptions {
  final BigInt numberOfOutputs;
  final AudioNodeOptions audioNodeOptions;

  const ChannelSplitterOptions({
    required this.numberOfOutputs,
    required this.audioNodeOptions,
  });

  @override
  int get hashCode => numberOfOutputs.hashCode ^ audioNodeOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelSplitterOptions &&
          runtimeType == other.runtimeType &&
          numberOfOutputs == other.numberOfOutputs &&
          audioNodeOptions == other.audioNodeOptions;
}
