// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../param.dart';
import '../periodic_wave.dart';
import 'audio_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assert_valid_channel_count_mode`, `assert_valid_channel_count`, `channel_config`, `clone`, `db_to_lin`, `default`, `fmt`, `fmt`, `lin_to_db`, `number_of_inputs`, `number_of_outputs`, `process`, `registration`, `set_channel_count_mode`, `set_channel_count`
// These types are ignored because they are not used by any `pub` functions: `DynamicsCompressorRenderer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DynamicsCompressorNode>>
@sealed
class DynamicsCompressorNode extends RustOpaque {
  // Not to be used by end users
  DynamicsCompressorNode.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DynamicsCompressorNode.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_DynamicsCompressorNode,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_DynamicsCompressorNode,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_DynamicsCompressorNodePtr,
  );

  Future<AudioParam> attack() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeAttack(
        that: this,
      );

  Future<AudioParam> knee() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeKnee(
        that: this,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DynamicsCompressorNode> newInstance(
          {required C context, required DynamicsCompressorOptions options}) =>
      RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeNew(
              context: context, options: options);

  Future<AudioParam> ratio() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeRatio(
        that: this,
      );

  Future<double> reduction() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeReduction(
        that: this,
      );

  Future<AudioParam> release() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeRelease(
        that: this,
      );

  Future<AudioParam> threshold() => RustLib.instance.api
          .webAudioApiNodeDynamicsCompressorDynamicsCompressorNodeThreshold(
        that: this,
      );
}

/// Options for constructing a [`DynamicsCompressorNode`]
class DynamicsCompressorOptions {
  final double attack;
  final double knee;
  final double ratio;
  final double release;
  final double threshold;
  final AudioNodeOptions audioNodeOptions;

  const DynamicsCompressorOptions({
    required this.attack,
    required this.knee,
    required this.ratio,
    required this.release,
    required this.threshold,
    required this.audioNodeOptions,
  });

  @override
  int get hashCode =>
      attack.hashCode ^
      knee.hashCode ^
      ratio.hashCode ^
      release.hashCode ^
      threshold.hashCode ^
      audioNodeOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DynamicsCompressorOptions &&
          runtimeType == other.runtimeType &&
          attack == other.attack &&
          knee == other.knee &&
          ratio == other.ratio &&
          release == other.release &&
          threshold == other.threshold &&
          audioNodeOptions == other.audioNodeOptions;
}
