[package]
name = "rust_lib_demo_web_audio_api_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { path = "../../flutter_rust_bridge/frb_rust" }
web-audio-api = "1.0.0-rc.6"
extend = "1.2.0"
