// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `DerefAudioRenderQuantumChannel`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioWorkletGlobalScope>>
@sealed
class AudioWorkletGlobalScope extends RustOpaque {
  // Not to be used by end users
  AudioWorkletGlobalScope.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioWorkletGlobalScope.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_AudioWorkletGlobalScope,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_AudioWorkletGlobalScope,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_AudioWorkletGlobalScopePtr,
  );

  BigInt get currentFrame => RustLib.instance.api
          .webAudioApiRenderProcessorAudioWorkletGlobalScopeGetCurrentFrame(
        that: this,
      );

  double get currentTime => RustLib.instance.api
          .webAudioApiRenderProcessorAudioWorkletGlobalScopeGetCurrentTime(
        that: this,
      );

  double get sampleRate => RustLib.instance.api
          .webAudioApiRenderProcessorAudioWorkletGlobalScopeGetSampleRate(
        that: this,
      );

  void set currentFrame(BigInt currentFrame) => RustLib.instance.api
      .webAudioApiRenderProcessorAudioWorkletGlobalScopeSetCurrentFrame(
          that: this, currentFrame: currentFrame);

  void set currentTime(double currentTime) => RustLib.instance.api
      .webAudioApiRenderProcessorAudioWorkletGlobalScopeSetCurrentTime(
          that: this, currentTime: currentTime);

  void set sampleRate(double sampleRate) => RustLib.instance.api
      .webAudioApiRenderProcessorAudioWorkletGlobalScopeSetSampleRate(
          that: this, sampleRate: sampleRate);
}
